import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import MiniKitProvider from "@/components/minikit-provider";
import dynamic from "next/dynamic";
import NextAuthProvider from "@/components/next-auth-provider";
import {Toaster} from "@/components/ui/toaster";
// import {Footer} from "@/components/footer";
import {Navbar} from "@/components/navbar";
import { Gate } from "@/components/gate"

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const ErudaProvider = dynamic(
		() => import("../components/eruda").then((c) => c.ErudaProvider),
		{
			ssr: false,
		}
	);
	return (
		<html lang="en">
			<body className={`${inter.className} h-screen w-screen`}>
				<NextAuthProvider>
					<ErudaProvider>
						<MiniKitProvider>
							<Gate>
								<div className="h-screen flex flex-col">
									<div className="fixed top-0 left-0 right-0 z-50">
										<Navbar />
									</div>
									<main className="flex-1 overflow-y-auto mt-[64px] mb-[64px]">
										{children}
									</main>
								</div>
							</Gate>
						</MiniKitProvider>
					</ErudaProvider>
				</NextAuthProvider>
				<Toaster />
			</body>
		</html>
	);
}
